# Generated by Django 3.2.5 on 2023-06-01 11:12

from django.db import migrations

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from datetime import datetime, timedelta
import time

def beginning(apps, schema_editor):
    
    # Суперпользователь id-1
    user = User.objects.create_superuser(username='root',
    email='travel060523@mail.ru',
    password='SsNn5678+-@', 
    last_login=datetime.now())
    print("Суперпользователь создан")
    
    # Группа менеджеров
    managers = Group.objects.get_or_create(name = 'Managers')
    managers = Group.objects.get(name='Managers')
    print("Группа менеджеров создана")
    
    # Пользователь с ролью менеджера id2
    user = User.objects.create_user(username='manager', password='Ss0066+-', email='manager@mail.ru', first_name='Менеджер', last_name='', last_login=datetime.now())
    managers.user_set.add(user)
    print("Менеджер добавлен в группу менеджеров")

    # Простые пользователи (заявители) id3-27
    user = User.objects.create_user(username='user1', password='Uu0066+-', email='user1@mail.ru', first_name='Дина', last_name='Мусина', last_login=datetime.now())
    user = User.objects.create_user(username='user2', password='Uu0066+-', email='user2@mail.ru', first_name='Адия', last_name='Жунусова', last_login=datetime.now())
    user = User.objects.create_user(username='user3', password='Uu0066+-', email='user3@mail.ru', first_name='Айнура', last_name='Кенина', last_login=datetime.now())
    user = User.objects.create_user(username='user4', password='Uu0066+-', email='user4@mail.ru', first_name='Рустем', last_name='Какимов', last_login=datetime.now())
    user = User.objects.create_user(username='user5', password='Uu0066+-', email='user5@mail.ru', first_name='Алишер', last_name='Кабдуалиев', last_login=datetime.now())
    user = User.objects.create_user(username='user6', password='Uu0066+-', email='user6@mail.ru', first_name='Бауржан', last_name='Арыкбаев', last_login=datetime.now())
    user = User.objects.create_user(username='user7', password='Uu0066+-', email='user7@mail.ru', first_name='Алишер', last_name='Танатаров', last_login=datetime.now())
    user = User.objects.create_user(username='user8', password='Uu0066+-', email='user8@mail.ru', first_name='Мерует', last_name='Искакова', last_login=datetime.now())
    user = User.objects.create_user(username='user9', password='Uu0066+-', email='user9@mail.ru', first_name='Ольга', last_name='Муравьева', last_login=datetime.now())
    user = User.objects.create_user(username='user10', password='Uu0066+-', email='user10@mail.ru', first_name='Ақжарқын', last_name='Сансызбаева', last_login=datetime.now())
    user = User.objects.create_user(username='user11', password='Uu0066+-', email='user11@mail.ru', first_name='Арайлым', last_name='Алматова', last_login=datetime.now())
    user = User.objects.create_user(username='user12', password='Uu0066+-', email='user12@mail.ru', first_name='Айгерім', last_name='Дүйсенбиева', last_login=datetime.now())
    user = User.objects.create_user(username='user13', password='Uu0066+-', email='user13@mail.ru', first_name='Салтанат', last_name='Зиноллаева', last_login=datetime.now())
    user = User.objects.create_user(username='user14', password='Uu0066+-', email='user14@mail.ru', first_name='Сейтқасым', last_name='Болат', last_login=datetime.now())
    user = User.objects.create_user(username='user15', password='Uu0066+-', email='user15@mail.ru', first_name='Сара', last_name='Фазилова', last_login=datetime.now())
    user = User.objects.create_user(username='user16', password='Uu0066+-', email='user16@mail.ru', first_name='Бектас', last_name='Ерсейіт', last_login=datetime.now())
    user = User.objects.create_user(username='user17', password='Uu0066+-', email='user17@mail.ru', first_name='Диас', last_name='Мырзаш', last_login=datetime.now())
    user = User.objects.create_user(username='user18', password='Uu0066+-', email='user18@mail.ru', first_name='Нұржан', last_name='Жүрсінбек', last_login=datetime.now())
    user = User.objects.create_user(username='user19', password='Uu0066+-', email='user19@mail.ru', first_name='Дина', last_name='Жағыпар', last_login=datetime.now())
    user = User.objects.create_user(username='user20', password='Uu0066+-', email='user20@mail.ru', first_name='Жастілек', last_name='Жасталап', last_login=datetime.now())
    user = User.objects.create_user(username='user21', password='Uu0066+-', email='user21@mail.ru', first_name='Еркебұлан', last_name='Қадыхан', last_login=datetime.now())
    user = User.objects.create_user(username='user22', password='Uu0066+-', email='user22@mail.ru', first_name='Молдир', last_name='Бутабекова', last_login=datetime.now())
    user = User.objects.create_user(username='user23', password='Uu0066+-', email='user23@mail.ru', first_name='Аружан', last_name='Таурбекова', last_login=datetime.now())
    user = User.objects.create_user(username='user24', password='Uu0066+-', email='user24@mail.ru', first_name='Алтынай', last_name='Қожанова', last_login=datetime.now())
    user = User.objects.create_user(username='user25', password='Uu0066+-', email='user25@mail.ru', first_name='Эльнара', last_name='Иминова', last_login=datetime.now())
    print("Созданы простые пользователи")

    
    ##### Вопросы/ответы #####
    
    Answers = apps.get_model("info", "Answers")

    answers = Answers()
    answers.datea = datetime.now() - timedelta(days=30)
    answers.question = 'Вопрос'
    answers.answer = 'Ответ'
    answers.user_id = 3
    answers.specialist_id = 2
    answers.save()

    answers = Answers()
    answers.datea = datetime.now() - timedelta(days=30)
    answers.question = 'Вопрос'
    answers.answer = 'Ответ'
    answers.user_id = 4
    answers.specialist_id = 2
    answers.save()

    answers = Answers()
    answers.datea = datetime.now() - timedelta(days=30)
    answers.question = 'Вопрос'
    answers.answer = 'Ответ'
    answers.user_id = 5
    answers.specialist_id = 2
    answers.save()

    answers = Answers()
    answers.datea = datetime.now() - timedelta(days=30)
    answers.question = 'Вопрос'
    answers.answer = 'Ответ'
    answers.user_id = 6
    answers.specialist_id = 2
    answers.save()

    ##### Отзывы #####

    Reviews = apps.get_model("info", "Reviews")
    
    reviews = Reviews()
    reviews.dater = datetime.now() - timedelta(days=30)
    reviews.details = 'Отзыв'
    reviews.user_id = 3
    reviews.save()

    reviews = Reviews()
    reviews.dater = datetime.now() - timedelta(days=25)
    reviews.details = 'Отзыв'
    reviews.user_id = 4
    reviews.save()

    reviews = Reviews()
    reviews.dater = datetime.now() - timedelta(days=20)
    reviews.details = 'Отзыв'
    reviews.user_id = 5
    reviews.save()
    
    reviews = Reviews()
    reviews.dater = datetime.now() - timedelta(days=15)
    reviews.details = 'Отзыв'
    reviews.user_id = 6
    reviews.save()

    
    ##### Новости #####

    News = apps.get_model("info", "News")
    
    news = News()
    news.daten = datetime.now() - timedelta(days=35)
    news.title = 'Заголовок'
    news.details = """Новость
    """
    news.photo = 'images/news1.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=30)
    news.title = 'Заголовок'
    news.details = """Новость
    """
    news.photo = 'images/news2.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=25)
    news.title = 'Заголовок'
    news.details = """Новость

    """
    news.photo = 'images/news3.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=20)
    news.title = 'Заголовок'
    news.details = """Новость
    """
    news.photo = 'images/news4.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=15)
    news.title = 'Заголовок'
    news.details = """Новость
    """
    news.photo = 'images/news5.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=10)
    news.title = 'Заголовок'
    news.details = """Новость
    """
    news.photo = 'images/news6.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=5)
    news.title = 'Заголовок'
    news.details = """Новость
    """
    news.photo = 'images/news7.jpeg' 
    news.save()
    
    print("News Ok")


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(beginning),       
    ]

